### ISSUE TITLE
Completion fails on item selection

### ISSUE THREAD

**Issue by steelsojka** [nvim-lua/completion-nvim#145] opened 2020-07-07 14:26 UTC
When accepting a completion item (LSP item in this case), the below error is thrown.

![Screen Shot 2020-07-07 at 9 12 00 AM](https://user-images.githubusercontent.com/2062154/86795870-9f7f3300-c033-11ea-9b9a-8b58babaa35f.png)

- Please read through [this section](https://github.com/haorenW1025/completion-nvim/wiki/trouble-shooting) before posting a bug report.

**My testing minimal init.vim**
```vim
call plug#begin('~/.local/share/nvim/plugged')
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/completion-nvim'
call plug#end()
lua require'nvim_lsp'.tsserver.setup{on_attach=require'completion'.on_attach}
au Filetype lua setl omnifunc=v:lua.vim.lsp.omnifunc
" Use <Tab> and <S-Tab> to navigate through popup menu
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" Set completeopt to have a better completion experience
set completeopt=menuone,noinsert,noselect
```

**How to reproduce**
Trigger the completion menu with the lsp source. Select an item.

**Expected behavior**
No error should be thrown.

**Comment by steelsojka** [comment] 2020-07-07 14:34
Setting the plugin to a commit before this commit c8ff1cccdabea51c32515085d69faaab48b97920 fixes it.

**Comment by haorenW1025** [comment] 2020-07-08 05:36
Can't reproduce on my side using sumneko_lua, pyls and clangd...Can you check see if the PR solve this issue?

**Comment by sgarcez** [comment] 2020-07-08 07:48
It seems to fix it for me, thanks @haorenW1025.

**Comment by steelsojka** [comment] 2020-07-08 11:59
@haorenW1025 It fixed the error but I get this when arrowing to an item and hitting "<cr>".

![Screen Shot 2020-07-08 at 6 55 25 AM](https://user-images.githubusercontent.com/2062154/86915982-7f5d7b80-c0e8-11ea-83de-3cc93d81f5b6.png)

**Comment by steelsojka** [comment] 2020-07-08 12:01
For clarity, I have this command in my config

```lua
steel.command [[inoremap <expr> <cr> pumvisible() ? "\<Plug>(completion_confirm_completion)" : "\<cr>"]]
```

**Comment by haorenW1025** [comment] 2020-07-08 13:24
@steelsojka That's weird... Can you see if deleting the view files (rm -rf ~/.local/share/nvim/view/*) help?

**Comment by yaegassy** [comment] 2020-07-08 13:26
I created this PR. How about this? https://github.com/nvim-lua/completion-nvim/pull/147

**Comment by haorenW1025** [comment] 2020-07-08 13:28
Ah yeah my bad this should be merged first...Feel free to reopen if this doesn't fix.

**Closed** 2020-07-08 13:29 UTC

**Comment by Shatur95** [comment] 2020-07-09 08:49
Helped for me, thanks!
