### ISSUE TITLE
[Completion stutter with Dart on slow machine]: completion.nvim is not as smooth as LSC, maybe 500ms debounce needed?

### ISSUE THREAD

**Issue by bluz71** [nvim-lua/completion-nvim#231] opened 2020-10-02 05:38 UTC
Hello again,

I am an [LSC](https://github.com/natebosch/vim-lsc) user that is looking at Neovim LSP + completion.nvim.

I am noticing that Neovim LSP + completion.nvim stutters more than LSC when completing Dart code in Flutter projects on **very slow** machines (e.g. my 2015 Core-M Macbook).

On normal machines I don't notice a difference between the two LSP/completion systems.
But on the slow I definitely do.

It appears that completion.nvim somehow is triggering greater CPU usage from the Dart language server when compared with LSC during auto-completion. For example 100% plus with completion.nvim compared with under 50% with LSC.

I do know that [LSC does emply a 500ms debounce](https://github.com/natebosch/vim-lsc/blob/cdfe09b608231f6df9bb825357f3e59c866243bd/autoload/lsc/file.vim#L94-L97) during auto-completion:

```viml
  let s:flush_timers[file_path] =
      \ timer_start(500,
      \   {_->s:FlushIfChanged(file_path, filetype)},
      \   {'repeat': 1})
```

I don't know what completion.nvim is doing but my question is whether a debounce is currently being used? If yes, what value? If no, then maybe an avenue worth exploring.

[Debouncing has been requested previously](https://github.com/nvim-lua/completion-nvim/issues/203#issuecomment-692595003):

> But a right behaviour doesn't always mean a good experience, maybe it should debounce & batch these requests instead of sending letter by letter

Secondly, LSC does no `isIncomplete` processing whilst completion.nvim does, maybe that's an issue, maybe it is not, but @hrsh7th did [state this previously](https://github.com/nvim-lua/completion-nvim/issues/203#issuecomment-693478997):

> Hi, The typescript-language-server does not support isIncomplete in my knowledge.
>
> But completion-nvim sends a request on each char.

Food for thought, maybe completion.nvim performance can be improved as follows:

- If not already debounced, add in debouncing, maybe with 500ms interval. We don't want completion after every character.

- Don't send `isIncomplete` if server does not support it

- Don't send `isIncomplete` on every character, use debouncing (maybe 500ms?)

- Maybe allow user to switch-off `isIncomplete`? I am not sure about this one, maybe `isIncomplete` won't be an issue if debouncing is done?

Anyway, for Dart on slow machines LSC definitely is much smoother than completion.nvim. Hopefully we can find out why and correct the performance issues?

I am more than willing to run tests as needed especially since a very slow machine is required to reproduce the issue.

Best regards.

**Comment by bluz71** [comment] 2020-10-04 02:24
Relevant comment by @prabirshrestha in #203:

> Author of [vim-lsp](https://github.com/prabirshrestha/vim-lsp) and [asyncomplete.vim](https://github.com/prabirshrestha/asyncomplete.vim) here.
> 
> debouncing is not enough. There are other smarter ways to fix perf which asyncomplete.vim and ncm uses which is similar to VSCode. I documented my findings of how vscode is performant at [roxma/nvim-completion-manager#30 (comment)](https://github.com/roxma/nvim-completion-manager/issues/30#issuecomment-283281158). You could do the same trick for completion-nvim. you might want to read the thread from start to get the best context.

**Comment by bluz71** [comment] 2020-10-05 01:58
Neovim LSP appears to be sending the full buffer content to the language server for every insert mode change via the `textDocument/didChange` event.

For comparison, the LSC plugin sends minimal byte range differences.

See [this post for details](https://github.com/nvim-lua/completion-nvim/issues/203#issuecomment-703356444).

The upstream Neovim LSP behaviour seems highly inefficient and could be an important factor for why language server CPU usage is far higher when using Neovim LSP + completion.nvim vs LSC.

**Comment by haorenW1025** [comment] 2020-10-15 05:24
Let's close this issue because it seems to be a duplicate of #203

**Closed by haorenW1025** 2020-10-15 05:24 UTC
