### ISSUE TITLE
Outdated results when user keeps typing and completion takes a long time

### ISSUE THREAD

**Issue by astier** [nvim-lua/completion-nvim#167] opened 2020-08-04 13:46 UTC
**My testing minimal init.vim**

```vim
cal plug#begin($XDG_DATA_HOME.'/nvim/plugins')
    Plug 'neovim/nvim-lsp'
    Plug 'nvim-lua/completion-nvim'
cal plug#end()
au bufenter * lua require'completion'.on_attach()
lua require'nvim_lsp'.pyls.setup{}
let g:completion_chain_complete_list = [{'complete_items': ['lsp']}]
se completeopt=menuone,noinsert
```

**My testing minimal python file**

```python
import numpy
numpy
```

**How to reproduce**
1. `pip install numpy`
2. Open minimal python file
3. Type fast `.r` after last `numpy` and let load results
4. Results should be like in the screenshot

![2020-08-04-154451_235x139_scrot](https://user-images.githubusercontent.com/36510152/89301073-7620e980-d669-11ea-81c4-585344cd11d4.png)

**Expected behavior**
The results from the above screenshot are the same results as if you would just type `.` after numpy. Completion-nvim ignores the `r` after the `.` If you type it slowly such that completion-nvim can keep up then the results as expected:

![2020-08-04-154413_822x156_scrot](https://user-images.githubusercontent.com/36510152/89301004-5b4e7500-d669-11ea-9012-9d09cbe5369e.png)

**Comment by haorenW1025** [comment] 2020-08-10 08:24
I've noticed this before but I think pyls is causing the slow response since completion-nvim have to wait for its result. Using pyls_ms may be better, but overall I think python's language server is all kind of slow...As for the outdated results it's a duplicate of #74 .

**Closed by haorenW1025** 2020-08-10 08:24 UTC

**Comment by astier** [comment] 2020-08-10 10:44
The slow response is because pyls uses jedi in the background for completion. Jedi performs lazy loading. For a big module like `numpy` it takes a while. Jedi does in fact caching. So the second time it should be fast but pyls breaks it. So when using pyls its always slow. But thats besides the point. Coc and deoplete somehow manage to handle this case correctly and dont show outdated results even when the loading takes a long time. Maybe when the completion is not finished but the user typed new characters then completion-nvim should just abort the old completion and start a new one with the new characters?
