### ISSUE TITLE
No import on Enter <CR> with vim-snip-integ jdtls

### ISSUE THREAD

**Issue by ChrisAmelia** [nvim-lua/completion-nvim#248] opened 2020-10-19 15:15 UTC
```
NVIM v0.5.0-752-g759a05407
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Commit: 857fb1b14644cf90

**My testing minimal init.vim**
```vim
set runtimepath^=~/.local/share/nvim/plugged/nvim-lspconfig
set runtimepath^=~/.local/share/nvim/plugged/completion-nvim
set runtimepath^=~/.local/share/nvim/plugged/vim-vsnip
set runtimepath^=~/.local/share/nvim/plugged/vim-vsnip-integ

set completeopt=menuone,noinsert,noselect

lua << EOF
    local nvim_lsp = require 'nvim_lsp'
    local root_pattern = nvim_lsp.util.root_pattern
    local on_attach_vim = function(client)
        require'completion'.on_attach(client)
    end

	require'nvim_lsp'.jdtls.setup{
            root_dir = root_pattern(".git", "pom.xml"),
            on_attach = on_attach_vim,
	}
EOF
```

**How to reproduce**
1. Create `Test.java` with:

```java
public class Test {

	public static void main(String[] args) {

	}


}
```

2. Inside main function, type `List`.

3. Look for `java.util.List` and press Enter:

![image](https://user-images.githubusercontent.com/16366403/96470379-83904d80-122e-11eb-9152-949578f00c1e.png)

4. Notice that `java.util.List` is not added (although, it is added by using `code_action()`). 

**Expected behavior**
`java.util.List` is automatically added to the import section when pressing Enter.
Removing `vim-snip-integ` makes it work.

**Comment by haorenW1025** [comment] 2020-10-21 08:13
Have you used the latest `vim-vsnip-integ` and `vim-vsnip`? I tried to reproduce but is seems to work on my side.

**Comment by hrsh7th** [comment] 2020-10-21 08:19
I think https://github.com/nvim-lua/completion-nvim/commit/669f90c5794cae8d6cb56f57c6347544eab28e52 causes it may be.

I recommend to use `do_complete_done` instead of `on_complete_done`.

**Comment by ChrisAmelia** [comment] 2020-10-21 09:03
> Have you used the latest `vim-vsnip-integ` and `vim-vsnip`? I tried to reproduce but is seems to work on my side.

Yes, I'm on the latest of both, respectively `4a076bea73e307` and `b08d78bb7df1f1d3b`.

> I recommend to use `do_complete_done` instead of `on_complete_done`.

Tried, the same issue still remains.

**Comment by hrsh7th** [comment] 2020-10-21 09:14
thank you for testing.

You should change as https://github.com/nvim-lua/completion-nvim/commit/669f90c5794cae8d6cb56f57c6347544eab28e52#diff-6392ae82b1c1f58e7721cb6d8b5fb7a83fc96533ad35da0d8633d14f2427a04dL102

**Comment by ChrisAmelia** [comment] 2020-10-21 09:26
> thank you for testing.
> 
> You should change as [669f90c#diff-6392ae82b1c1f58e7721cb6d8b5fb7a83fc96533ad35da0d8633d14f2427a04dL102](https://github.com/nvim-lua/completion-nvim/commit/669f90c5794cae8d6cb56f57c6347544eab28e52#diff-6392ae82b1c1f58e7721cb6d8b5fb7a83fc96533ad35da0d8633d14f2427a04dL102)

Thanks, this fixes it.

**Comment by haorenW1025** [comment] 2020-10-21 17:38
Hmm I was having some issue with `do_complete_done` in the past so I change it, I'll see if that an issue on my config now. If so, we should go back to using `do_complete_done`.

**Comment by haorenW1025** [comment] 2020-10-21 18:04
@hrsh7th If I use `do_complete_done` normal snippets expansion will not work on my side. but that's because I disable the autocmd in vsnip-integ. After re-enable the autocmd it works as expected. However I remember before when disabling the autocmd it works fine, do you make some changes in `vim-vsnip-integ`?

**Comment by hrsh7th** [comment] 2020-10-22 04:50
Yes, I fixed the problem of duplicated snippet expansion 2 months ago (I thought it has no breaking change).

I think it was a potential bug of vim-vsnip-integ and it was fixed so you can restore the commit.

**Comment by haorenW1025** [comment] 2020-10-22 05:37
Should be fixed in the latest commit.

**Closed by haorenW1025** 2020-10-22 05:37 UTC

**Comment by hrsh7th** [comment] 2020-10-22 05:38
Thank you for your work!

**Comment by ChrisAmelia** [comment] 2020-10-22 08:08
Commit 2b90524e4fe9d78584ada2942231a913402ff74d seems to prevent the auto-import from functionning.
Commit 669f90c5794cae8d6cb56f57c63475 works fine before the above one.

**Comment by ChrisAmelia** [comment] 2020-10-22 08:24
In commit ecaccc3c91d919a2, the removing of these lines prevent the auto-import:

```vim
  if vim.fn.exists("#vsnip_integ") then
    api.nvim_command("augroup vsnip_integ")
      api.nvim_command("autocmd!")
    api.nvim_command("augroup end")
  end
```

**Comment by hrsh7th** [comment] 2020-10-22 08:26
I will check it.

**Comment by hrsh7th** [comment] 2020-10-22 12:00
It's bug of vim-vsnip-integ.

I don't know why but vim-vsnip-integ receives `CompleteDone` before `do_complete_done`...

I will investigate it.

**Comment by hrsh7th** [comment] 2020-10-22 12:13
@ChrisAmelia It should be fixed now by latest vim-vsnip-integ.

**Comment by ChrisAmelia** [comment] 2020-10-22 13:52
Yes, works fine. Thanks.
