### ISSUE TITLE
error on startup - attempt to index field 'handlers' (a nil value)

### ISSUE THREAD

**Issue by pljanot** [nvim-lua/completion-nvim#274] opened 2020-11-17 02:20 UTC
After recent plugin updates, I run into an error which I couldn't deal with.
I browse a little bit and see that there were updates near hover.lua:250 (#268) 
I would appreciate any help, thank you.

**My testing minimal init.vim**
[gist](https://gist.github.com/pljanot/4528c391f9e7dcee0ab6c6dd4eff73d0)

**How to reproduce**
* download most recent nighlt build nvim
* install & update all plugins to most recent version
* run ./nvim with provided init file.
* error expected:
> Error executing lua ...t/.vim/plugged2/completion-nvim/lua/completion/hover.lua:250: attempt to index field 'handlers' (a nil value)

**Expected behavior**
* nvim loads `completion-nvim` plugin without error

**Comment by kflak** [comment] 2020-11-17 07:07
Can confirm, same issue here on Arch Linux, nvim-nightly.

**Comment by ngtinsmith** [comment] 2020-11-17 07:22
Same, I was able able to fix now by though by renaming the **key** on `../completion-nvim/lua/completion/hover.lua` file.

Just search for `client.config.callbacks` and `vim.lsp.callbacks` and rename the from **callbacks** key to **handlers**.

**Comment by lithammer** [comment] 2020-11-17 07:41
I suspect this means your Neovim version is simply too old. From the look of things, the [Neovim nightly on AUR](https://aur.archlinux.org/packages/neovim-nightly-git/) hasn't been updated since August, and you need something newer than https://github.com/neovim/neovim/pull/12655 which was merged 4 days ago.

@ngtinsmith that just means you're running an old version of completion-nvim because master doesn't contain the word "callbacks" (outside of a comment):

```console
$ grep -ri callbacks completion-nvim
completion-nvim/lua/completion.lua:  -- TODO: Modified this if lua callbacks for autocmd is merged
```

**Comment by willfish** [comment] 2020-11-17 08:01
I'm using asdf to install neovim nightly which uses neovim tags to determine what are the available versions to build. My nightly version also isn't compatible with this change.

**Comment by willfish** [comment] 2020-11-17 08:02
Looking at the age of the nightly tag it's 6 days old which is consistent with your comment about the change being merged 4 days ago.

**Comment by willfish** [comment] 2020-11-17 08:05
I'm not sure what the nightly tagging process is but I'm guessing this would be sorted by generating a new tag in neovim and making the new api for callbacks -> handlers available. I'm wondering whether all lsp configuration plugins are up-to-date with their references to handlers, though. I guess the dust needs to settle.

Locally I reverted the callback naming change and did the following in the hover.lua file:

```diff
 M.autoOpenHoverInPopup = function()
   if vim.fn.pumvisible() ~= 1 then return end
   for _, client in pairs(vim.lsp.buf_get_clients(0)) do
-    local default_callback = client.config.callbacks['textDocument/hover'] or vim.lsp.callbacks['textDocument/hover']
+    local default_callback = client.callbacks['textDocument/hover'] or vim.lsp.callbacks['textDocument/hover']
     if default_callback ~= callback_function then
-      client.config.callbacks['textDocument/hover'] = callback_function
+      client.callbacks['textDocument/hover'] = callback_function
     end
   end
```

**Comment by ngtinsmith** [comment] 2020-11-17 08:18
@lithammer I see, you're right, my version was 25 days behind. just updated it's working now as is. :thumbsup:

**Comment by kflak** [comment] 2020-11-17 09:00
Aha, that makes sense. My problem now is that the `neovim-nightly-git` from aur refuses to build on my system. Which is probably more of a packaging issue than a nvim issue.

**Comment by salkin-mada** [comment] 2020-11-17 09:07
@kflak maybe try the one based on the nightly tarballz `neovim-nightly`

**Comment by jaydorsey** [comment] 2020-11-17 14:20
I had to change one other line in hover.lua (line 250)

```diff
- M.default_handler = vim.lsp.handlers[handler]
+ M.default_handler = vim.lsp.callbacks[handler]
```

Same nvim version as others, the currently nightly which is 6 days behind

**Comment by Iron-E** [comment] 2020-11-18 03:17
If you're getting this message, it means that your Neovim version is too old. #268 was merged due to a change made a few days ago.

**Comment by kflak** [comment] 2020-11-18 08:30
Seems the `neovim-nightly-git` package pulls from the `nightly` tag, which is now 7 days old. Is there a way to (generate these tags more frequently? Should I submit an issue in neovim?

**Comment by pibone** [comment] 2020-11-18 09:59
I've just changed that line until the nightly catches up with a fix compatible with the new 'handlers'  field:

```diff
- M.default_handler = vim.lsp.handlers[handler]
+ M.default_handler = (vim.lsp.handlers or vim.lsp.callbacks)[handler]
```

**Comment by duganchen** [comment] 2020-11-18 21:11
It's definitely still happening with the latest neovim AppImage from the GitHub page, which is:

NVIM v0.5.0-828-g0a95549d6

Do I just need to try again tomorrow?

**Comment by Iron-E** [comment] 2020-11-18 21:19
If any of you need to build neovim from source you can use my update script in the meantime:

```sh
ROOT_DIR="$HOME/Repos/neovim"
BUILD_DIR="$ROOT_DIR/build"
SOURCE_DIR="$ROOT_DIR/src"

# Extract the source and if there were no errors, remove the previous build.
cd $SOURCE_DIR
git pull &&
	make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=$BUILD_DIR &&
	rm -rf $BUILD_DIR &&
	make install &&
	git reset --hard; git clean -fxd &&
	cd -
ln -s "$BUILD_DIR/bin/nvim" ~/bin/nim
```

This will create a temporary binary `nim` on the nightly. All you have to do is:

1. Edit `$ROOT_DIR` to a directory of your choosing
2. Clone neovim/neovim to `$ROOT_DIR/src`
3. Run the build script.

Hopefully this should tide you over.

**Comment by mhanberg** [comment] 2020-11-19 01:53
I just build the latest master and am still seeing this issue. This is quite strange. I built neovim with `make CMAKE_BUILD_TYPE=Release`

**Comment by mhanberg** [comment] 2020-11-19 01:59
> Seems the `neovim-nightly-git` package pulls from the `nightly` tag, which is now 7 days old. Is there a way to (generate these tags more frequently? Should I submit an issue in neovim?

Their TravisCI pipeline is on hold due to cost so they're porting it to GitHub Actions, and that effort is in progress. @kflak

**Comment by kflak** [comment] 2020-11-19 07:32
Good to know, thanks!

**Comment by kflak** [comment] 2020-11-20 07:38
I built from source according to @Iron-E's excellent instructions without a hitch and did a clean reinstall of completion.nvim. Now I am getting this error: 
```Error detected while processing /home/kf/.config/nvim/plugin/packer_compiled.vim:
line  165:
E5108: Error executing lua ...ite/pack/packer/start/completion-nvim/lua/completion.lua:253: bad argument #1 to 'len' (string expected, got nil)```

**Comment by haorenW1025** [comment] 2020-11-20 09:06
Sorry for the inconvenience everyone, this is caused by some breaking changes of neovim core(to make built-in LSP better). This shouldn't be happen too often though. As an user of the neovim nightly version, I highly recommend building neovim from source since it shouldn't be hard and you can easily follow any huge changes.

Also hugh thanks for @Iron-E  @lithammer for the help on answering question when I'm not around. Highly appreciate:)

If you still ran into issues with newest version of neovim, please of a new issue.

**Closed by haorenW1025** 2020-11-20 09:06 UTC

**Comment by lithammer** [comment] 2020-11-20 09:15
> Also hugh thanks for @Iron-E @lithammer for the help on answering question when I'm not around. Highly appreciate:)

No worries! I'm happy to help 🙂

**Comment by noelevans** [comment] 2020-11-25 12:53
If you are using AUR, this is fixed in neovim-git (but still causing problems in neovim-nightly and neovim-nightly-git)

**Comment by fuadnafiz98** [comment] 2020-11-30 19:37
Any update on this?? I am using the latest AppImage

**Comment by mhanberg** [comment] 2020-11-30 20:06
@fuadnafiz98 The nightly builds are still not up. You can follow along here: https://github.com/neovim/neovim/issues/13312.

I suggest compiling from source in the meantime. If you use `asdf` for other stuff, you can also use it for neovim: https://github.com/richin13/asdf-neovim.

**Comment by fuadnafiz98** [comment] 2020-12-01 07:17
Thanks, @mhanberg, I build from the source and have done a couple of things. 

1. Build `Neovim` from source
2. Change this lines in `~/.vim/plugged/compilation-nvim/lua/completion/hover.lua`:
```lua
 M.autoOpenHoverInPopup = function()
   if vim.fn.pumvisible() ~= 1 then return end
   for _, client in pairs(vim.lsp.buf_get_clients(0)) do
-    local default_callback = client.config.callbacks['textDocument/hover'] or vim.lsp.callbacks['textDocument/hover']
+    local default_callback = client.callbacks['textDocument/hover'] or vim.lsp.callbacks['textDocument/hover']
     if default_callback ~= callback_function then
-      client.config.callbacks['textDocument/hover'] = callback_function
+      client.callbacks['textDocument/hover'] = callback_function
     end
   end
```
3. Also changed this line of the same file on line `250`
```lua
- M.default_handler = vim.lsp.handlers[handler]
+ M.default_handler = (vim.lsp.handlers or vim.lsp.callbacks)[handler]
```
4. changed the line in `~/.vim/plugged/compilation-nvim/lua/completion/signature_help.lua` on line `33` :
```lua
- local handler = client and client.handlers['textDocument/signatureHelp']
+ local handler = client and client.callbacks['textDocument/signatureHelp']
```
